# Generated by Django 4.2.1 on 2023-06-18 15:43

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Header',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='static/images/', verbose_name='Изображение')),
                ('tag1', models.CharField(max_length=100, verbose_name='Тег 1')),
                ('tag2', models.CharField(max_length=100, verbose_name='Тег 2')),
                ('btnText', models.CharField(max_length=100, verbose_name='Текст в кнопке')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
