version: '3.3'

services:
  db:
    image: postgres
    restart: always
    env_file:
      - .env
    volumes:
      - postgresdata:/var/lib/postgresql/data

  nginx:
    volumes:
      - nginx_cache:/var/lib/nginx/proxy_cache
      - static:/app/www/static/
      - local_static:/var/www/local_static/
      - nuxt:/var/www/nuxt:ro
      - static:/var/www/static/:ro
      - acme.sh:/acme.sh:delegated
      - certs:/etc/nginx/certs
    build:
      context: ./nginx
    depends_on:
      - server
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env

  server:
    restart: always
    build:
      context: ./server
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static:/app/static/
    entrypoint: ./entrypoint.sh
    command: python manage.py runserver 0.0.0.0:8000

  frontend:
    restart: always
    build:
      context: ./client
    command: npm run start
    env_file:
      - .env
    volumes:
      - nuxt:/app/nuxt_volume:delegated


volumes:
  nginx_cache:
  local_static:
  static:
  postgresdata:
  nuxt:
  acme.sh:
  certs:
