version: '3.3'

services:
  db:
    image: postgres
    restart: always
    env_file: .env
    environment:
      POSTGRES_USER: ${DATABASE_USERNAME}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgresdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - strapi

  nginx:
    restart: always
    volumes:
      - nginx_cache:/var/lib/nginx/proxy_cache
      - static:/app/www/static/
      - local_static:/var/www/local_static/
      - nuxt:/var/www/nuxt:ro
      - static:/var/www/static/:ro
      - acme.sh:/acme.sh:delegated
      - certs:/etc/nginx/certs
    build:
      context: ./nginx
    ports:
      - 80:80
      - 443:443
    env_file: .env
    networks:
      - strapi

  strapi:
    build:
      context: ./strapi
    restart: unless-stopped
    env_file: .env
    environment:
      DATABASE_CLIENT: ${DATABASE_CLIENT}
      DATABASE_HOST: db
      DATABASE_PORT: ${DATABASE_PORT}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USERNAME: ${DATABASE_USERNAME}
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      PUBLIC_URL: ${PUBLIC_URL}
      JWT_SECRET: ${JWT_SECRET}
      ADMIN_JWT_SECRET: ${ADMIN_JWT_SECRET}
      APP_KEYS: ${APP_KEYS}
      NODE_ENV: ${NODE_ENV}
    ports:
      - "1337:1337"
    volumes:
      - ./strapi/config:/app/config
      - ./strapi/src:/app/src
      - ./strapi/package.json:/app/package.json
      - ./strapi/package-lock.lock:/app/package-lock.lock
      - ./strapi/.env:/app/.env
      - ./strapi/public/uploads:/app/public/uploads
    depends_on:
      - db
    networks:
      - strapi

  frontend:
    restart: always
    build:
      context: ./frontend
    command: npm run start
    env_file: .env
    environment:
      SERVER_API_URL: ${SERVER_API_URL}
    volumes:
      - nuxt:/app/nuxt_volume:delegated
    ports:
      - "3000:3000"
    depends_on:
      - strapi
      - nginx
    networks:
      - strapi

networks:
  strapi:

volumes:
  postgresdata:
  nginx_cache:
  local_static:
  static:
  nuxt:
  acme.sh:
  certs: