version: '3.9'

services:
  db:
    image: mysql:latest
    restart: always
    env_file:
      - .env
    volumes:
      - db-data:/var/lib/mysql


  nginx:
    volumes:
      - nginx_cache:/var/lib/nginx/proxy_cache
      - static:/app/static/
    build:
      context: ./nginx
    depends_on:
      - server
    ports:
      - 80:80
      - 443:443
    env_file:
      - .env

  server:
    restart: always
    build:
      context: ./server
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - static:/app/static/

  frontend:
    restart: always
    build:
      context: ./client
    env_file:
      - .env
    volumes:
      - nuxt:/app/nuxt_volume:delegated


volumes:
  static:
  db-data:
  nginx_cache:
  nuxt:
