# Generated by Django 4.2.1 on 2023-06-18 15:43

import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectStepsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Этапы выполнения работы', max_length=255, verbose_name='Заголовок страницы')),
            ],
            options={
                'verbose_name': 'Этапы выполнения работы',
                'verbose_name_plural': 'Этапы выполнения работы',
            },
        ),
        migrations.CreateModel(
            name='ProjectSteps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('text', ckeditor.fields.RichTextField(blank=True, verbose_name='Описание')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Порядок')),
                ('page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='projectStepsPage.projectstepspage', verbose_name='Этапы выполнения работы')),
            ],
            options={
                'verbose_name': 'Этап Выполнения',
                'verbose_name_plural': 'Этап Выполнения',
                'ordering': ('order',),
            },
        ),
    ]
