# Generated by Django 4.2.1 on 2023-06-18 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MenuItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, verbose_name='Название пункта')),
                ('value', models.CharField(max_length=255, verbose_name='Алиас')),
            ],
        ),
    ]
