#!/usr/local/bin/python

from os import getenv
from socket import error as socket_error
from socket import socket, AF_INET, SOCK_STREAM
from time import sleep

tries: int = 0
host: str = str(getenv("MYSQL_HOST", "db"))
port: int = int(getenv("MYSQL_PORT", "3306"))

sock: socket = socket(AF_INET, SOCK_STREAM)

while tries <= 1800:
    try:
        sock.connect((host, port))
        sock.close()
        break
    except socket_error as err:
        sleep(0.1)
        tries += 1
