name: CI/CD

on:
  workflow_dispatch:
  push:
    branches: [ master ]

env:
  DEPLOY_PATH: /home/a0548906/domains/lyaman-askerova.kz/public_html/
  BUILD_SCRIPT_OUTPUT: dist/

jobs:
  build-frontend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: client

    steps:
      - name: Prepare environments
        uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: npm ci

      - name: Generate bundle
        run: npm run generate

      - name: Install SSH Key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          known_hosts: unnecessary

      - name: Adding Known Hosts
        run: ssh-keyscan -p ${{ secrets.SSH_PORT}} -H ${{ secrets.REMOTE_HOST }}  >> ~/.ssh/known_hosts

      - name: rsync deployments
        uses: burnett01/rsync-deployments@5.2.1
        with:
          switches: -avzr --delete
          path: ${{ env.BUILD_SCRIPT_OUTPUT }}
          remote_path: ${{ env.DEPLOY_PATH }}
          remote_host: ${{ secrets.REMOTE_HOST }}
          remote_user: ${{ secrets.REMOTE_USER }}
          remote_key: ${{ secrets.SSH_PRIVATE_KEY }}

#      - name: Deploy to Server
#        uses: easingthemes/ssh-deploy@main
#        env:
#          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
#          SOURCE: ${{ env.BUILD_SCRIPT_OUTPUT }}
#          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
#          REMOTE_USER: ${{ secrets.REMOTE_USER }}
#          TARGET: ${{ env.DEPLOY_PATH }}
